export const domainIconMapping: { [key: string]: string } = {
  art: "palette",
  coins: "coins",
  crypto: "bitcoin",
  data: "database",
  "e-commerce": "shopping-bag",
  education: "graduation-cap",
  entertainment: "film",
  fitness: "dumbbell",
  fortnite: "fort-awesome",
  fintech: "chart-area",
  "food-delivery": "utensils",
  gaming: "gamepad",
  healthcare: "heartbeat",
  indie: "hand-holding-heart",
  "live shopping": "shopping-bag",
  music: "music",
  "social-media": "users",
  steam: "steam",
  sustainability: "leaf",
  technology: "laptop",
  travel: "plane",
};
